# Generated by Django 4.1.7 on 2023-04-08 10:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_usercource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCource',
            new_name='UserCourse',
        ),
    ]
